# Generated by Django 5.1.6 on 2025-10-23 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='note',
            options={'ordering': ['-uploaded_at'], 'verbose_name': 'Note', 'verbose_name_plural': 'Notes'},
        ),
    ]
