# Generated by Django 5.1.6 on 2025-10-21 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_note_file_name_note_file_path_alter_note_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='file',
        ),
    ]
